# Generated by Django 2.2.1 on 2019-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesummary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='avg_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='avg_tr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='avg_wr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='aid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='com_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tr_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wr_score',
            field=models.FloatField(),
        ),
    ]
