# Generated by Django 2.2.1 on 2019-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesummary', '0002_auto_20190518_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='aid',
            field=models.IntegerField(),
        ),
    ]
