# Generated by Django 2.2.1 on 2019-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesummary', '0003_auto_20190518_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='avg_com',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='avg_tr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='avg_wr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
